### ISSUE TITLE
Create a page to monitor fine-tuning progress

### ISSUE THREAD

**Issue by katsudoon1** [OsushiGeekCamp/openai-finetuning-helper#18]

**Comment by niimurank** [comment]
今回のプロジェクトはJSONファイルだと見にくくて、使いづらいところから来ている。
実際に使う際にはIDが必要になる。けど、ユーザーはファイル名やモデル名で覚えているため、一画面でどちらも確認できるようにしたい

**Comment by niimurank** [comment]
モデル一覧を作るにはjob一覧の情報が必要なので、結局job一覧を先に作らないといけない。
なら、1ページずつ作る必要性がないかもしれない。

ステータスが成功しているものだけで、絞り込んで表示させればjob一覧とモデル一覧兼用で１ページに纏められるのでは？

**Comment by k-taro56** [comment]
Related Issues: #19

**Comment by k-taro56** [comment]
> 今回のプロジェクトはJSONファイルだと見にくくて、使いづらいところから来ている。 実際に使う際にはIDが必要になる。けど、ユーザーはファイル名やモデル名で覚えているため、一画面でどちらも確認できるようにしたい

Is the policy not to display IDs to end-users?

**Comment by niimurank** [comment]
すでにマージされているListFilesのカラム名がIDでjob idと分かりづらいので、それぞれ変更をわかりやすいように変更すべき

**Comment by katsudoon1** [comment]
> > 今回のプロジェクトはJSONファイルだと見にくくて、使いづらいところから来ている。 実際に使う際にはIDが必要になる。けど、ユーザーはファイル名やモデル名で覚えているため、一画面でどちらも確認できるようにしたい
> 
> Is the policy not to display IDs to end-users?

By 'IDs', are you referring to the name of the Fine Tuned Model and the name of the training data file? If so, it would be better to take a look."

**Comment by katsudoon1** [comment]
> > 今回のプロジェクトはJSONファイルだと見にくくて、使いづらいところから来ている。 実際に使う際にはIDが必要になる。けど、ユーザーはファイル名やモデル名で覚えているため、一画面でどちらも確認できるようにしたい
> 
> Is the policy not to display IDs to end-users?



> モデル一覧を作るにはjob一覧の情報が必要なので、結局job一覧を先に作らないといけない。 なら、1ページずつ作る必要性がないかもしれない。
> 
> ステータスが成功しているものだけで、絞り込んで表示させればjob一覧とモデル一覧兼用で１ページに纏められるのでは？

"#18 and #19 can be done together using this method.
#18 and #19 should be replaced with a single job listing page."
