### ISSUE TITLE
Create a Home page

### ISSUE THREAD

**Issue by k-taro56** [OsushiGeekCamp/openai-finetuning-helper#34]

**Comment by katsudoon1** [comment]
"Let's discuss the requirements for the homepage. Some initial ideas:

- Links to each page
- Instructions on how to use this web app
- A text box for entering the API key."

**Comment by k-taro56** [comment]
It would be nice to have a screen to enter the API key. 
It would also be nice to have a link to an editor page that can be used without an API key.

**Comment by katsudoon1** [comment]
It might be best to leave the links to each page to #42.

**Comment by k-taro56** [comment]
Isn't it independent of task #42?
But I think you would have to go to a some page after entering the API key.

**Comment by k-taro56** [comment]
I misunderstood. You mean you intend to implement links to each page in #42.

> It would be nice to have a screen to enter the API key. It would also be nice to have a link to an editor page that can be used without an API key.

I'll start with this content.
