### ISSUE TITLE
[file-list] Disable or Hide Quick Start Button when unable to start

### ISSUE THREAD

**Issue by k-taro56** [OsushiGeekCamp/openai-finetuning-helper#68]

**Comment by k-taro56** [comment]
#60

**Comment by katsudoon1** [comment]
Why not just display only the files that can be quick started ?

**Comment by katsudoon1** [comment]
The idea of putting all the files on the same table might not be a good one.

**Comment by katsudoon1** [comment]
Do you only want to display the training files and the fine-tuning result files? If so, I have a suggestion:

Display only the training files on this page, and link the fine-tuning result files to the job list.

This is because the fine-tuning result files are created as a result of the job.

**Comment by katsudoon1** [comment]
Resolved in #170.

**Comment by k-taro56** [comment]
close #170

**Comment by katsudoon1** [comment]
Resolved in #170
